// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_railway_timetable/test/features/timetable/data/repository/thsr_timetable_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_railway_timetable/features/timetable/data/datasource/tdx_thsr_api_service.dart'
    as _i2;
import 'package:flutter_railway_timetable/features/timetable/data/dto/tdx_thsr_response_dto.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TdxThsrApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTdxThsrApiService extends _i1.Mock implements _i2.TdxThsrApiService {
  MockTdxThsrApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TdxThsrDailyTrainDto>> getDailyTimetable(
    String? origin,
    String? destination,
    String? trainDate, {
    String? format = 'JSON',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDailyTimetable,
              [origin, destination, trainDate],
              {#format: format},
            ),
            returnValue: _i3.Future<List<_i4.TdxThsrDailyTrainDto>>.value(
              <_i4.TdxThsrDailyTrainDto>[],
            ),
          )
          as _i3.Future<List<_i4.TdxThsrDailyTrainDto>>);

  @override
  _i3.Future<List<_i4.TdxThsrStationDto>> getStations({
    String? format = 'JSON',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getStations, [], {#format: format}),
            returnValue: _i3.Future<List<_i4.TdxThsrStationDto>>.value(
              <_i4.TdxThsrStationDto>[],
            ),
          )
          as _i3.Future<List<_i4.TdxThsrStationDto>>);

  @override
  _i3.Future<List<_i4.TdxThsrODFareItemDto>> getODFare(
    String? originStationId,
    String? destinationStationId, {
    String? format = 'JSON',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getODFare,
              [originStationId, destinationStationId],
              {#format: format},
            ),
            returnValue: _i3.Future<List<_i4.TdxThsrODFareItemDto>>.value(
              <_i4.TdxThsrODFareItemDto>[],
            ),
          )
          as _i3.Future<List<_i4.TdxThsrODFareItemDto>>);
}
