// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_railway_timetable/test/features/widget_config/domain/update_widget_stations_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_railway_timetable/features/widget_config/domain/entity/widget_station.dart'
    as _i4;
import 'package:flutter_railway_timetable/features/widget_config/domain/repository/i_widget_station_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IWidgetStationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWidgetStationRepository extends _i1.Mock
    implements _i2.IWidgetStationRepository {
  MockIWidgetStationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> tableExists() =>
      (super.noSuchMethod(
            Invocation.method(#tableExists, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.WidgetStation>> getStations(String? system) =>
      (super.noSuchMethod(
            Invocation.method(#getStations, [system]),
            returnValue: _i3.Future<List<_i4.WidgetStation>>.value(
              <_i4.WidgetStation>[],
            ),
          )
          as _i3.Future<List<_i4.WidgetStation>>);

  @override
  _i3.Future<void> setFront({
    required String? fromName,
    required String? fromId,
    required String? toName,
    required String? toId,
    required String? system,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setFront, [], {
              #fromName: fromName,
              #fromId: fromId,
              #toName: toName,
              #toId: toId,
              #system: system,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> initDefaultsIfNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#initDefaultsIfNeeded, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
