// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_railway_timetable/test/features/timetable/data/timetable_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_railway_timetable/features/timetable/data/datasource/tdx_tra_api_service.dart'
    as _i2;
import 'package:flutter_railway_timetable/features/timetable/data/dto/tdx_response_dto.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TdxTraApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTdxTraApiService extends _i1.Mock implements _i2.TdxTraApiService {
  MockTdxTraApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.TdxTimetableResponseDto> getDailyTimetable(
    String? origin,
    String? destination,
    String? trainDate, {
    String? format = 'JSON',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDailyTimetable,
              [origin, destination, trainDate],
              {#format: format},
            ),
            returnValue: _i3.Future<_i4.TdxTimetableResponseDto>.value(
              const _i4.TdxTimetableResponseDto(),
            ),
          )
          as _i3.Future<_i4.TdxTimetableResponseDto>);

  @override
  _i3.Future<List<_i4.TdxStationDto>> getStations({
    String? format = 'JSON',
    int? top = 500,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getStations, [], {#format: format, #top: top}),
            returnValue: _i3.Future<List<_i4.TdxStationDto>>.value(
              <_i4.TdxStationDto>[],
            ),
          )
          as _i3.Future<List<_i4.TdxStationDto>>);
}
